const places=[
{id:1,name:'Old Joo Chiat Story House',cat:'history',label:'LOCAL STORY',distance:'0.8 km',area:'Joo Chiat',desc:'A prototype community story stop exploring how Joo Chiat changed from village life to today’s cultural precinct.',story:'Then & Now: compare memories of the neighbourhood with what you see today.',detail:'Discover how everyday streets, homes and businesses can hold stories that are easy to miss when you are simply passing through.'},
{id:2,name:'Geylang Serai Food Stories',cat:'food',label:'FOOD & TRADITION',distance:'1.4 km',area:'Geylang Serai',desc:'A prototype discovery trail about people, recipes and traditions behind one of Singapore’s culturally rich food areas.',story:'Meet the makers: trace one dish from family recipe to modern Singapore.',detail:'Food becomes an entry point into heritage — the people, languages, celebrations and memories behind what we eat.'},
{id:3,name:'Katong Paper Craft Studio',cat:'craft',label:'MADE IN SG',distance:'2.1 km',area:'Katong',desc:'A sample community workshop concept keeping traditional paper craft techniques alive through hands-on making.',story:'Try it yourself: learn a paper craft technique and add your creation to a community wall.',detail:'Instead of only reading about a tradition, you participate in a small activity and leave with something you made.'},
{id:4,name:'Kampong Glam Community Stories',cat:'community',label:'LIVING HERITAGE',distance:'3.2 km',area:'Kampong Glam',desc:'A prototype walking experience connecting architecture, community memories and contemporary cultural life.',story:'Look beyond the landmark: collect three stories from the people and places around the precinct.',detail:'Heritage is not frozen in time. This discovery connects older stories with the people, businesses and communities shaping the area today.'}
];
const events=[
{id:11,title:'Traditional Wayang Workshop',date:'Sat · 12 Sep · 2:00 PM',place:'Kampong Glam',distance:'3.2 km',price:15,eligible:true,cat:'craft',desc:'Sample event: learn the basics of a traditional performance art through a hands-on session.'},
{id:12,title:'Stories of Old Katong',date:'Sun · 13 Sep · 10:30 AM',place:'Katong',distance:'2.1 km',price:0,eligible:true,cat:'history',desc:'Sample event: a guided walk through overlooked neighbourhood histories.'},
{id:13,title:'Peranakan Food & Family Recipes',date:'Sat · 19 Sep · 4:00 PM',place:'Joo Chiat',distance:'0.8 km',price:25,eligible:true,cat:'food',desc:'Sample event: cook, taste and hear the family stories behind classic Peranakan dishes.'},
{id:14,title:'Voices of the Neighbourhood',date:'Sun · 20 Sep · 3:00 PM',place:'Geylang Serai',distance:'1.4 km',price:10,eligible:false,cat:'community',desc:'Sample event: listen to community memories and add your own story to a shared neighbourhood map.'}
];
const defaultState={balance:100,points:180,completed:2,discoveries:4,saved:[],activities:[{date:'SEP 06',title:'Traditional Wayang Workshop',text:'You experienced a traditional art form.',points:50},{date:'SEP 03',title:'Joo Chiat Story House',text:'You discovered a lesser-known local story.',points:40}],prefs:[]};
let state=JSON.parse(localStorage.getItem('heritageConnectState')||'null')||defaultState;
let activeCategory='all',mapCategory='all',passOnly=false,pendingEvent=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function saveState(){localStorage.setItem('heritageConnectState',JSON.stringify(state));}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2800)}
function showView(id){$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+id)?.classList.add('active-view');$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});renderJourney();if(id==='pass')renderPass();}
function updateBalances(){['#headerBalance','#bannerBalance','#walletBalance'].forEach(sel=>{const e=$(sel);if(e)e.textContent=state.balance});const bar=$('#walletBar');if(bar)bar.style.width=Math.max(0,state.balance)+'%';}
function placeMatches(p){const q=($('#searchInput')?.value||'').toLowerCase().trim();const cat=activeCategory==='all'||p.cat===activeCategory;const search=!q||[p.name,p.area,p.cat,p.desc].join(' ').toLowerCase().includes(q);return cat&&search;}
function renderPlaces(){const grid=$('#placeGrid');if(!grid)return;const data=places.filter(placeMatches);$('#resultCount').textContent=`${data.length} discovery${data.length===1?'':'ies'}`;grid.innerHTML=data.length?data.map(p=>{const saved=state.saved.includes(p.id);return `<article class="place-card"><div class="place-image"><span class="tag">${p.label}</span></div><div class="place-body"><h3>${p.name}</h3><p>${p.desc}</p><div class="meta"><span>⌖ ${p.distance}</span><span>${p.cat}</span></div><div class="card-actions"><button class="small-btn" data-detail="${p.id}">Explore story →</button><button class="save-btn ${saved?'saved':''}" data-save="${p.id}" aria-label="${saved?'Remove from saved':'Save place'}">${saved?'♥':'♡'}</button></div></div></article>`}).join(''):`<div class="empty-state">No discoveries match that search. Try another category or search term.</div>`;}
function renderEvents(){const grid=$('#eventGrid');if(!grid)return;const data=events.filter(e=>!passOnly||e.eligible);grid.innerHTML=data.map(e=>`<article class="event-card"><span class="event-date">${e.date}</span><h3>${e.title}</h3><p>${e.desc}</p><div class="meta"><span>⌖ ${e.place} · ${e.distance}</span><span>${e.price?'$'+e.price:'Free'}</span></div><div class="event-bottom">${e.eligible?'<span class="eligible">CULTURE PASS</span>':'<span></span>'}<button class="btn primary" data-book="${e.id}">${e.price?'Book':'Join free'}</button></div></article>`).join('');}
function renderPass(){const grid=$('#passEventGrid');if(!grid)return;grid.innerHTML=events.filter(e=>e.eligible).map(e=>`<article class="event-card"><span class="event-date">${e.date}</span><h3>${e.title}</h3><p>${e.desc}</p><div class="meta"><span>⌖ ${e.place}</span><span>$${e.price}</span></div><div class="event-bottom"><span class="eligible">CULTURE PASS</span><button class="btn primary" data-book="${e.id}">Use credits</button></div></article>`).join('');updateBalances();}
function renderNearby(){const list=$('#nearbyList');if(!list)return;const data=places.filter(p=>mapCategory==='all'||p.cat===mapCategory);list.innerHTML=data.map(p=>`<div class="near-item"><span class="num">0${p.id}</span><div><h3>${p.name}</h3><p>${p.distance} · ${p.area} · ${p.cat}</p><button data-detail="${p.id}">View story →</button></div></div>`).join('');$$('.map-marker').forEach(m=>m.classList.toggle('dim',mapCategory!=='all'&&places.find(p=>p.id===+m.dataset.placeId)?.cat!==mapCategory));}
function renderJourney(){const pts=$('#points');if(pts)pts.textContent=state.points;const cc=$('#completedCount');if(cc)cc.textContent=state.completed;const dc=$('#discoveriesCount');if(dc)dc.textContent=state.discoveries;const sc=$('#savedCount');if(sc)sc.textContent=state.saved.length;const pb=$('#progressBar');if(pb)pb.style.width=Math.min(100,state.points/3)+'%';const saved=$('#savedList');if(saved)saved.innerHTML=state.saved.length?state.saved.map(id=>{const p=places.find(x=>x.id===id);return `<div class="saved-item"><div><b>${p.name}</b><small>${p.distance} · ${p.cat}</small></div><button data-detail="${p.id}">Open</button></div>`}).join(''):`<div class="empty-state">Save a place from Discover and it'll appear here.</div>`;const timeline=$('#timeline');if(timeline)timeline.innerHTML=state.activities.map(a=>`<div class="timeline-item"><span class="date">${a.date}</span><div><b>${a.title}</b><p>${a.text}</p></div><strong>+${a.points}</strong></div>`).join('');}
function openDetail(id){const p=places.find(x=>x.id===+id);if(!p)return;const saved=state.saved.includes(p.id);$('#detailContent').innerHTML=`<div class="detail-cover"></div><div class="detail-body"><span class="kicker">${p.label} · ${p.distance}</span><h2>${p.name}</h2><p>${p.desc}</p><div class="story-box"><strong>WHY IT'S WORTH DISCOVERING</strong><br>${p.detail}<br><br><strong>TRY THIS</strong><br>${p.story}</div><button class="btn primary full" data-save="${p.id}">${saved?'♥ Saved to my journey':'♡ Save this discovery'}</button></div>`;$('#detailModal').classList.remove('hidden');}
function openBooking(id){const e=events.find(x=>x.id===+id);if(!e)return;pendingEvent=e;$('#bookingTitle').textContent=e.title;$('#bookingDescription').textContent=`${e.date} · ${e.place}. ${e.desc}`;$('#bookingPrice').textContent=e.price?'$'+e.price:'Free';$('#bookingModal').classList.remove('hidden');}
function confirmBooking(){if(!pendingEvent)return;const e=pendingEvent;if(e.eligible&&e.price>state.balance){showToast('Not enough demo Culture Pass credit.');return}if(e.eligible)state.balance-=e.price;state.completed++;state.points+=30;state.activities.unshift({date:'SEP 07',title:e.title,text:e.price?'You booked a Culture Pass eligible experience.':'You joined a free cultural experience.',points:30});saveState();updateBalances();renderJourney();$('#bookingModal').classList.add('hidden');showToast(`Demo booking added to your journey ✓`);}
function toggleSave(id){id=+id;const p=places.find(x=>x.id===id);if(!p)return;if(state.saved.includes(id)){state.saved=state.saved.filter(x=>x!==id);showToast('Removed from saved places');}else{state.saved.push(id);showToast('Saved to My Journey ♥');}saveState();renderPlaces();renderJourney();if(!$('#detailModal').classList.contains('hidden'))openDetail(id);}
function init(){
 $$('.nav-btn,.mobile-nav button,.brand,.pass-pill').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();showView(b.dataset.view)}));
 $$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>{showView('discover');setTimeout(()=>$('#'+b.dataset.scroll)?.scrollIntoView({behavior:'smooth'}),50)}));
 $$('.chip').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.category){$$('#categoryFilters .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeCategory=b.dataset.category;renderPlaces()}if(b.dataset.mapFilter){$$('.map-filters .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');mapCategory=b.dataset.mapFilter;renderNearby()}}));
 $('#searchInput')?.addEventListener('input',renderPlaces);$('#clearSearch')?.addEventListener('click',()=>{$('#searchInput').value='';renderPlaces();$('#searchInput').focus()});
 $('#passFilter')?.addEventListener('click',()=>{passOnly=!passOnly;$('#passFilter').classList.toggle('active',passOnly);renderEvents()});
 document.addEventListener('click',e=>{const detail=e.target.closest('[data-detail]');if(detail)openDetail(detail.dataset.detail);const save=e.target.closest('[data-save]');if(save)toggleSave(save.dataset.save);const book=e.target.closest('[data-book]');if(book)openBooking(book.dataset.book);const close=e.target.closest('[data-close]');if(close)$('#'+close.dataset.close).classList.add('hidden');const marker=e.target.closest('[data-place-id]');if(marker)openDetail(marker.dataset.placeId)});
 $('#confirmBooking')?.addEventListener('click',confirmBooking);$('#zoomIn')?.addEventListener('click',()=>showToast('Map zoomed in — demo interaction'));$('#zoomOut')?.addEventListener('click',()=>showToast('Map zoomed out — demo interaction'));
 $('#challengeBtn')?.addEventListener('click',()=>{state.points+=50;state.completed++;state.activities.unshift({date:'SEP 07',title:'Then & Now Challenge',text:'You started a challenge to compare Singapore past and present.',points:50});saveState();renderJourney();showToast('Challenge started — +50 points!')});
 $('#editPrefs')?.addEventListener('click',()=>{$('#onboarding').classList.remove('hidden');state.prefs.forEach(p=>$$(`[data-pref="${p}"]`).forEach(b=>b.classList.add('selected')))});$('#savePreferences')?.addEventListener('click',()=>{state.prefs=$$('.interest-picker button.selected').map(b=>b.dataset.pref);saveState();$('#onboarding').classList.add('hidden');showToast('Your discovery feed has been updated ✦')});
 $$('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')}));
 if(!localStorage.getItem('heritageConnectOnboarded')){$('#onboarding').classList.remove('hidden');localStorage.setItem('heritageConnectOnboarded','1')}
 $$('.interest-picker button').forEach(b=>b.addEventListener('click',()=>b.classList.toggle('selected')));
 renderPlaces();renderEvents();renderNearby();renderJourney();renderPass();updateBalances();
}
document.addEventListener('DOMContentLoaded',init);
