import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,MapPin,Bookmark,Compass,User,ArrowLeft,ArrowRight,ExternalLink,MessageCircle,Send,Utensils,Landmark,BookOpen,Ticket,Heart,ChevronRight,Globe2,X} from 'lucide-react';
import './styles-v2.css';

const PASS='https://www.sgculturepass.gov.sg/?lang=en';
const EVENTS='https://www.sgculturepass.gov.sg/events';
const IMG={
 kampong:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Kampong_Lorong_Buangkok_entrance.jpg',
 shelter:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Tiong_Bahru_Air_Raid_Shelter_-_2023-0506.jpg',
 fuyong:'https://stacked-editorial.sgp1.digitaloceanspaces.com/editorial/wp-content/uploads/2022/06/15115159/fuyong-estate-landed-road-2.jpg',
 laksa:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Katong_Laksa.jpg',
 kaya:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Kaya_toast_from_Ya_Kun_Kaya_Toast%2C_Singapore_-_20160813.jpg',
 temple:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Thian_Hock_Keng_Temple_-_Singapore.jpg',
 mosque:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sultan_Mosque_03.jpg',
 indian:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sri_Veeramakaliamman_Temple_Singapore.jpg',
 peranakan:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Peranakan_Museum_Singapore_2014.jpg'
};
const places=[
{id:'p1',name:'Kampong Lorong Buangkok',area:'Buangkok',category:'Places',era:'1956 → now',image:IMG.kampong,eyebrow:'LIVING HERITAGE',desc:'Singapore’s last surviving mainland kampong, shaped by Chinese and Malay families and a strong spirit of gotong royong.',facts:['Established in 1956','Chinese and Malay community','Living residential community'],access:'Respect residents and private property. This is a living neighbourhood, not a theme park.'},
{id:'p2',name:'Tiong Bahru Air-Raid Shelter',area:'Tiong Bahru',category:'Places',era:'WWII',image:IMG.shelter,eyebrow:'UNDER YOUR FEET',desc:'A civilian air-raid shelter beneath Block 78 that connects an everyday HDB neighbourhood to wartime Singapore.',facts:['WWII civilian history','Under Block 78','Part of Tiong Bahru heritage'],access:'Follow current site access rules and do not enter closed areas.'},
{id:'p3',name:'Fuyong Estate',area:'Bukit Timah',category:'Places',era:'1950s',image:IMG.fuyong,eyebrow:'BEFORE MODERN HDB',desc:'An early affordable housing estate beside former kampongs, revealing how Singapore’s neighbourhoods changed.',facts:['1950s estate','Linked to Lee Kong Chian','Kampong-era landscape'],access:'Explore public areas only and respect residents.'}
];
const foods=[
{id:'f1',name:'Katong Laksa',region:'Peranakan / East Coast',image:IMG.laksa,desc:'A spicy coconut noodle dish strongly associated with Katong and the food memories of the East.',learn:'Food is one of the easiest ways to see how migration, trade and local ingredients become Singaporean identity.'},
{id:'f2',name:'Kaya Toast & Kopi',region:'Kopitiam culture',image:IMG.kaya,desc:'Toast, kaya, butter, soft-boiled eggs and kopi — a breakfast ritual shared across generations.',learn:'Kopitiams became everyday meeting places where different communities ate, worked and socialised.'}
];
const cultures=[
{id:'c1',name:'Chinese Singaporean heritage',tag:'LANGUAGE · FOOD · BELIEF',image:IMG.temple,color:'coral',desc:'Explore traditions shaped by migration, clan networks, festivals, food and places of worship.',items:['Thian Hock Keng and temple traditions','Chinese dialect groups and clan associations','Food traditions such as dim sum, noodles and tea'],prompt:'Why are there so many Chinese dialect groups in Singapore?'},
{id:'c2',name:'Malay heritage',tag:'LANGUAGE · KAMPONG · FAITH',image:IMG.kampong,color:'yellow',desc:'Discover Malay kampong life, language, music, foodways and the communities that shaped Singapore long before independence.',items:['Kampong life and gotong royong','Malay language and cultural traditions','Hari Raya, music, dance and food'],prompt:'What does gotong royong mean?'},
{id:'c3',name:'Indian Singaporean heritage',tag:'FAITH · MIGRATION · FOOD',image:IMG.indian,color:'blue',desc:'Trace Indian migration, religious traditions, businesses, food and neighbourhoods such as Little India.',items:['Sri Veeramakaliamman Temple','Deepavali and community traditions','South Indian and North Indian food cultures'],prompt:'Why is Little India historically important?'},
{id:'c4',name:'Peranakan culture',tag:'MIXED HERITAGE · HOME · FOOD',image:IMG.peranakan,color:'purple',desc:'Learn how Straits Chinese culture developed through a blend of Chinese, Malay and other regional influences.',items:['Nyonya food and kueh','Beadwork, textiles and dress','Peranakan homes and family traditions'],prompt:'What makes Peranakan culture different?'}
];
const religions=[
{name:'Buddhism',desc:'Explore beliefs, temples, festivals and community traditions in Singapore.',image:IMG.temple},
{name:'Islam',desc:'Learn about mosques, Malay-Muslim heritage and traditions such as Hari Raya.',image:IMG.mosque},
{name:'Hinduism',desc:'Discover temple traditions, festivals and the history of Indian communities.',image:IMG.indian},
{name:'Christianity',desc:'Explore churches, schools and communities that form part of Singapore’s religious landscape.',image:IMG.peranakan}
];
const events=[
['Art of Stroke: An Introduction to Traditional Chinese Calligraphy','From $100'],['Crafting Moments: The Art of Letterpress','From $80'],['FRAMED: Murder Mystery at National Gallery Singapore','From $30'],['Kueh Magnet Making Workshop','From $46'],['A Peranakan Legacy: A Journey Through Time','From $12'],['Chinatown Escape Game: Feast of Fury','From $45'],['Savouring Chinatown: Art, Heritage & River Views','From $100'],['Sentosa Culture & Heritage Pass','From $100']
].map((x,i)=>({id:i,title:x[0],price:x[1]}));
const open=url=>window.open(url,'_blank','noopener,noreferrer');

function App(){
 const [page,setPage]=useState('home'),[detail,setDetail]=useState(null),[saved,setSaved]=useState(()=>JSON.parse(localStorage.getItem('hc-saved')||'[]')),[query,setQuery]=useState('');
 const [chat,setChat]=useState(false);
 const save=id=>setSaved(a=>{const n=a.includes(id)?a.filter(x=>x!==id):[...a,id];localStorage.setItem('hc-saved',JSON.stringify(n));return n});
 const go=(p)=>{setDetail(null);setPage(p);window.scrollTo({top:0,behavior:'smooth'})};
 const results=useMemo(()=>places.filter(x=>(x.name+' '+x.area+' '+x.desc).toLowerCase().includes(query.toLowerCase())),[query]);
 return <div className="app">
  <header><button className="brand" onClick={()=>go('home')}><b>HC</b><span>HERITAGE<br/>CONNECT</span></button><nav>{[['home','Discover',Compass],['places','Places',MapPin],['food','Food',Utensils],['cultures','Cultures',Globe2],['learn','Learn',BookOpen],['events','Experiences',Ticket]].map(([p,l,I])=><button key={p} className={page===p?'active':''} onClick={()=>go(p)}><I size={15}/>{l}</button>)}</nav><div className="headerActions"><div className="search"><Search size={16}/><input value={query} onChange={e=>{setQuery(e.target.value);go('places')}} placeholder="Search Singapore's stories"/></div><button className="pass" onClick={()=>open(PASS)}>SG Culture Pass <ExternalLink size={13}/></button><button className="saved" onClick={()=>go('saved')}><Bookmark size={17}/><i>{saved.length}</i></button></div></header>
  {detail?<Detail type={detail.type} item={detail.item} back={()=>setDetail(null)} save={save} saved={saved} open={open}/>:<main>{page==='home'&&<Home go={go} open={setDetail}/>} {page==='places'&&<Places items={results} open={setDetail} save={save} saved={saved}/>} {page==='food'&&<Food open={setDetail}/>} {page==='cultures'&&<Cultures open={setDetail}/>} {page==='learn'&&<Learn go={go}/>} {page==='events'&&<Events/>} {page==='saved'&&<Saved ids={saved} save={save} open={setDetail}/>}</main>}
  <Chatbot open={chat} setOpen={setChat}/>
  <footer><div><b>HERITAGE CONNECT</b><p>The Singapore you walk past without knowing the story behind it.</p></div><div><b>EXPLORE</b><button onClick={()=>go('places')}>Places</button><button onClick={()=>go('food')}>Food</button><button onClick={()=>go('cultures')}>Cultures & religions</button></div><div><b>OFFICIAL</b><button onClick={()=>open(PASS)}>SG Culture Pass ↗</button><button onClick={()=>open(EVENTS)}>Official event catalogue ↗</button></div></footer>
  <nav className="mobileNav">{[['home','Discover',Compass],['places','Places',MapPin],['food','Food',Utensils],['cultures','Culture',Globe2],['learn','Learn',BookOpen]].map(([p,l,I])=><button key={p} onClick={()=>go(p)} className={page===p?'active':''}><I/><span>{l}</span></button>)}</nav>
 </div>
}
function Home({go,open}){return <>
 <section className="hero"><div className="heroCopy"><span className="eyebrow">SINGAPORE, BUT DEEPER</span><h1>You know Singapore.<br/><em>Do you know its stories?</em></h1><p>Not another list of tourist spots. Discover the food, faiths, cultures, people and hidden places that make Singapore what it is.</p><div className="heroButtons"><button className="primary" onClick={()=>go('places')}>Start exploring <ArrowRight/></button><button className="textBtn" onClick={()=>go('cultures')}>Meet the cultures <ChevronRight/></button></div><div className="heroStats"><span><b>01</b> PLACES</span><span><b>02</b> FOOD</span><span><b>03</b> PEOPLE & CULTURES</span></div></div><div className="heroPhoto"><img src={IMG.kampong}/><div><small>BUANGKOK · LIVING HERITAGE</small><h2>Kampong Lorong Buangkok</h2><button onClick={()=>open({type:'place',item:places[0]})}>Open full story ↗</button></div></div></section>
 <section className="choose"><span>WHAT DO YOU WANT TO DISCOVER?</span><div><button onClick={()=>go('places')}><Landmark/><b>PLACES</b><small>Hidden sites & history</small></button><button onClick={()=>go('food')}><Utensils/><b>FOOD</b><small>Recipes with a story</small></button><button onClick={()=>go('cultures')}><Globe2/><b>CULTURES</b><small>People, identity & traditions</small></button><button onClick={()=>go('learn')}><BookOpen/><b>LEARN</b><small>Explain it simply</small></button></div></section>
 <section className="homeSection"><div className="sectionHead"><div><span>START HERE</span><h2>Stories you won't<br/>find on a postcard.</h2></div><button onClick={()=>go('places')}>See all stories ↗</button></div><div className="storyGrid">{places.map((p,i)=><article className={i===0?'big':''} key={p.id} onClick={()=>open({type:'place',item:p})}><img src={p.image}/><div><small>{p.eyebrow}</small><h3>{p.name}</h3><p>{p.area} · {p.era}</p></div></article>)}</div></section>
 <section className="cultureStrip"><div><span>ONE ISLAND. MANY STORIES.</span><h2>Learn the cultures<br/><em>behind Singapore.</em></h2><p>Go beyond “Chinese, Malay, Indian and Others”. See how migration, religion, food, language and everyday life overlap.</p><button className="primary" onClick={()=>go('cultures')}>Explore cultures <ArrowRight/></button></div><div className="cultureMini">{cultures.slice(0,3).map(c=><article key={c.id} onClick={()=>open({type:'culture',item:c})}><img src={c.image}/><b>{c.name}</b><small>{c.tag}</small></article>)}</div></section>
 <section className="foodTeaser"><div className="sectionHead"><div><span>FOOD IS HERITAGE TOO</span><h2>Eat something.<br/><em>Understand something.</em></h2></div><button onClick={()=>go('food')}>Explore food ↗</button></div><div className="foodCards">{foods.map(f=><article key={f.id} onClick={()=>open({type:'food',item:f})}><img src={f.image}/><div><small>{f.region}</small><h3>{f.name}</h3><p>{f.desc}</p></div></article>)}</div></section>
 <section className="passCall"><div><span>SG CULTURE PASS</span><h2>Found something you want to do?</h2><p>Heritage Connect helps you discover. The official SG Culture Pass handles eligibility, credits and ticketing.</p><button onClick={()=>open(EVENTS)}>Browse official activities <ExternalLink/></button></div><div className="passBadge">$100<small>ELIGIBLE CITIZENS</small></div></section>
 </>}
function Places({items,open,save,saved}){return <section className="listing"><div className="pageTitle"><span>DISCOVER</span><h1>Places with<br/><em>a past.</em></h1><p>Tap any card. Every story opens into its own page — context, facts, access notes and related culture.</p></div><div className="cards">{items.map(p=><article className="placeCard" key={p.id} onClick={()=>open({type:'place',item:p})}><div><img src={p.image}/><span>{p.eyebrow}</span><button onClick={e=>{e.stopPropagation();save(p.id)}}>{saved.includes(p.id)?<Heart fill="currentColor"/>:<Bookmark/>}</button></div><section><small>{p.area} · {p.era}</small><h2>{p.name}</h2><p>{p.desc}</p><b>Open full story ↗</b></section></article>)}</div></section>}
function Food({open}){return <section className="listing"><div className="pageTitle"><span>FOOD & MEMORY</span><h1>What we eat<br/><em>has a history.</em></h1><p>Recipes, rituals and neighbourhoods — because heritage is something you can taste, not just read.</p></div><div className="cards foodPage">{foods.map(f=><article className="foodCard" key={f.id} onClick={()=>open({type:'food',item:f})}><img src={f.image}/><div><small>{f.region}</small><h2>{f.name}</h2><p>{f.desc}</p><b>Why does this food matter? ↗</b></div></article>)}</div><div className="learnBanner"><b>TRY THIS</b><h2>Ask the chatbot: “What food should I try if I want to learn about Peranakan culture?”</h2></div></section>}
function Cultures({open}){return <section className="listing"><div className="pageTitle"><span>PEOPLE · IDENTITY · TRADITION</span><h1>Singapore is<br/><em>many stories.</em></h1><p>Learn about ethnic and cultural communities without reducing them to stereotypes. Start with history, then explore food, faith, language and everyday life.</p></div><div className="cultureGrid">{cultures.map(c=><article key={c.id} className={'cultureCard '+c.color} onClick={()=>open({type:'culture',item:c})}><img src={c.image}/><div><small>{c.tag}</small><h2>{c.name}</h2><p>{c.desc}</p><b>Enter culture story ↗</b></div></article>)}</div><div className="religion"><div><span>FAITH & COMMUNITY</span><h2>Religions are part<br/>of Singapore's story.</h2><p>Learn respectfully about beliefs, places of worship, festivals and the communities around them.</p></div><div className="religionGrid">{religions.map((r,i)=><article key={r.name}><img src={r.image}/><div><small>0{i+1}</small><h3>{r.name}</h3><p>{r.desc}</p></div></article>)}</div></div></section>}
function Learn({go}){return <section className="listing learn"><div className="pageTitle"><span>LEARN WITHOUT THE LECTURE</span><h1>Got a question?<br/><em>Start here.</em></h1><p>Short explainers that connect Singapore's past to what you see today.</p></div><div className="questionGrid">{['Why are there so many places of worship in Singapore?','How did kampongs shape modern Singapore?','Why is food such a big part of our identity?','What does multiculturalism look like in everyday life?','Why are some heritage places hidden or restricted?','How did migration shape Singapore’s neighbourhoods?'].map((q,i)=><button key={q} onClick={()=>document.getElementById('chat-input')?.focus()}><span>0{i+1}</span><b>{q}</b><ChevronRight/></button>)}</div><div className="learnCTA"><BookOpen/><div><h2>Or just ask the Heritage Guide.</h2><p>The chatbot sits at the bottom of every page so you don't have to know what to search for.</p></div><button className="primary" onClick={()=>document.getElementById('chat-input')?.focus()}>Ask a question <MessageCircle/></button></div></section>}
function Events(){return <section className="listing"><div className="pageTitle"><span>OFFICIAL SG CULTURE PASS</span><h1>Things to<br/><em>actually do.</em></h1><p>These are discovery highlights. Availability, dates, prices and eligibility can change — always continue to the official site.</p><button className="primary" onClick={()=>open(EVENTS)}>View full official catalogue <ExternalLink/></button></div><div className="eventGrid">{events.map(e=><article key={e.id}><div className="eventNo">{String(e.id+1).padStart(2,'0')}</div><small>SG CULTURE PASS</small><h2>{e.title}</h2><b>{e.price}</b><button onClick={()=>open(EVENTS)}>Open official listing <ExternalLink/></button></article>)}</div></section>}
function Detail({type,item,back,save,saved,open}){const isPlace=type==='place';return <section className="detail"><button className="back" onClick={back}><ArrowLeft/> Back to explore</button><div className="detailHero"><img src={item.image}/><div><span>{item.eyebrow||item.tag||item.region}</span><h1>{item.name}</h1><p>{item.desc}</p>{isPlace&&<small>{item.area} · {item.era}</small>}<div className="detailActions">{isPlace&&<button className="primary" onClick={()=>save(item.id)}>{saved.includes(item.id)?'Saved':'Save this story'} <Bookmark/></button>}<button className="outline" onClick={()=>document.getElementById('chat-input')?.focus()}>Ask about this <MessageCircle/></button></div></div></div><div className="detailBody"><article><span>THE STORY</span><h2>{type==='culture'?'More than a label.':type==='food'?'More than a dish.':'Look closer.'}</h2><p>{item.learn||item.desc+' This page is designed to give you the context first, then the reason to experience it.'}</p>{item.facts&&<ul>{item.facts.map(x=><li key={x}>{x}</li>)}</ul>}{item.items&&<ul>{item.items.map(x=><li key={x}>{x}</li>)}</ul>}{item.access&&<div className="access"><b>ACCESS & RESPECT</b><p>{item.access}</p></div>}</article><aside><b>KEEP EXPLORING</b><button onClick={()=>open({type:'culture',item:cultures[0]})}>Chinese heritage <ArrowRight/></button><button onClick={()=>open({type:'food',item:foods[0]})}>Food with a story <ArrowRight/></button><button onClick={()=>open({type:'place',item:places[1]})}>Another hidden place <ArrowRight/></button></aside></div></section>}
function Saved({ids,save,open}){const list=places.filter(p=>ids.includes(p.id));return <section className="listing"><div className="pageTitle"><span>YOUR COLLECTION</span><h1>Stories you<br/><em>don't want to lose.</em></h1></div>{list.length?<div className="cards">{list.map(p=><article className="placeCard" key={p.id} onClick={()=>open({type:'place',item:p})}><div><img src={p.image}/><button onClick={e=>{e.stopPropagation();save(p.id)}}><Heart fill="currentColor"/></button></div><section><small>{p.area}</small><h2>{p.name}</h2><p>{p.desc}</p></section></article>)}</div>:<div className="empty"><Bookmark/><h2>Nothing saved yet.</h2><p>Save a story when something makes you want to know more.</p></div>}</section>}
function Chatbot({open,setOpen}){const [msgs,setMsgs]=useState([{from:'bot',text:'Hey! I’m your Heritage Guide. Ask me anything about Singapore’s places, food, cultures, religions or history.'}]);const [text,setText]=useState('');const reply=q=>{const s=q.toLowerCase();let a=s.includes('food')?'Try asking about Katong laksa, kaya toast, Peranakan food or how migration shaped Singapore’s cuisine.':s.includes('malay')||s.includes('gotong')?'Gotong royong means mutual help/community cooperation. It is an important idea in Malay kampong life.':s.includes('relig')||s.includes('mosque')?'I can explain Singapore’s religious communities, places of worship and festivals — ask me about Buddhism, Islam, Hinduism or Christianity.':s.includes('culture')?'Singapore’s cultures are shaped by migration, trade, language, religion, food and everyday community life. Tell me which community you want to explore.':s.includes('place')?'Try asking “What is special about Kampong Lorong Buangkok?” or “Why is Tiong Bahru’s air-raid shelter important?”':'I can help with Singapore heritage, food, cultures, religions and places. Try a more specific question!';setMsgs(m=>[...m,{from:'user',text:q},{from:'bot',text:a}]);setText('')};return <><button className={'chatFab '+(open?'hide':'')} onClick={()=>setOpen(true)}><MessageCircle/><span>Ask the Heritage Guide</span></button>{open&&<div className="chat"><div className="chatHead"><div><b>HERITAGE GUIDE</b><small>Singapore stories · Ask anything</small></div><button onClick={()=>setOpen(false)}><X/></button></div><div className="chatBody">{msgs.map((m,i)=><div key={i} className={m.from}>{m.text}</div>)}</div><div className="chatSuggestions"><button onClick={()=>reply('What food tells me about Singapore?')}>Food 🍜</button><button onClick={()=>reply('Explain gotong royong')}>Culture 🌏</button><button onClick={()=>reply('Tell me about a hidden place')}>Places 📍</button></div><div className="chatInput"><input id="chat-input" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&text.trim()&&reply(text)} placeholder="Ask a question..."/><button onClick={()=>text.trim()&&reply(text)}><Send/></button></div></div>}</>}
createRoot(document.getElementById('root')).render(<App/>);
