export const IMG = {
  fallback: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Kampong_Lorong_Buangkok_entrance.jpg',
  kampong: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Kampong_Lorong_Buangkok_entrance.jpg',
  shelter: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Tiong_Bahru_Air_Raid_Shelter_-_2023-0506.jpg',
  fuyong: 'https://stacked-editorial.sgp1.digitaloceanspaces.com/editorial/wp-content/uploads/2022/06/15115159/fuyong-estate-landed-road-2.jpg',
  gohChor: 'https://wonderwall.sg/images/default-source/content/dam/wonderwall/images/2021/11/adventures-at-home-lets-rediscover-balestier/goh-chor-temple.jpg.jpg?sfvrsn=d204c56_0',
  balestierMarket: 'https://danamic-media.danamic.org/danamic-production/2019/05/11231743/SS-NHBHW-4.jpg',
  malayFilm: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Former_Malay_Film_Productions_Studio_in_Balestier.jpg',
  burmese: 'https://cassette.sphdigital.com.sg/image/homedecor/9863c48a32c2f691e762696f8ebc5aa41ed9ce84528e52e60184b6346c248c60?q=85&w=660',
  thianHock: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Thian_Hock_Keng_Singapore.jpg',
  sriMariamman: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sri_Mariamman_Temple_in_Singapore.jpg',
  jamae: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Singapore_-_Temple_Street_-_Jamae_Chulia_Mosque_IMG_9236.jpg',
  sultan: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sultan_Mosque_03.jpg',
  malayHeritage: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Malay_Heritage_Centre_%28Side%29.jpg',
  tanTeng: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Wikimania_2023-Singapore_today-Little_India-03302.jpg/760px-Mapcarta.jpg',
  sriVeera: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sri_Veeramakaliamman_Temple_Singapore.jpg',
  abdulGafoor: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/2016_Singapur%2C_Little_India%2C_Meczet_Abdul_Gaffoor_%2801%29.jpg',
  littleIndiaArcade: 'https://cdn.forevervacation.com/uploads/tour/images/tour_258_5695.jpg',
  jooChiat: 'https://nowboarding.changiairport.com/content/dam/canowboarding/article-assets/live-local/year-end-events-and-festivities-in-singapore/joo-chiat-road-1080x770.jpg',
  nagore: 'https://ak-d.tripcdn.com/images/1mi6x224x8ufiuf7iB3B7.jpg?proc=source%2Ftrip',
  kwanIm: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Kwan_Im_Thong_Hood_Cho_Temple_%28Feb_2024%29.jpg',
  geylang: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Geylang_Serai_Market_aka_Pasar_Geylang_Serai_%282025%29_-_img_01.jpg',
  nationalMuseum: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/The_National_Museum_of_Singapore.jpg',
  changi: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Changi_Beach_Park%2C_Singapore_%28Unsplash%29.jpg',
  laksa: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Katong_Laksa.jpg',
  kaya: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Kaya_toast_from_Ya_Kun_Kaya_Toast%2C_Singapore_-_20160813.jpg',
  kueh: 'https://lp-cms-production.imgix.net/2024-09/Peranakan-dessert-37d3a33930a9.jpg?auto=format%2Ccompress&fit=crop&q=72',
  rotiJohn: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Roti_John_-_served.jpg',
  tauSarPiah: 'https://eatbook.sg/wp-content/uploads/2023/02/loong-fatt-tau-sar-piah-sweet-tau-sar-piah.jpg',
  hawker: 'https://imgix.theurbanlist.com/content/article/maxwell-food-centre.jpg'
};

const place = (id,name,area,tag,image,desc,story,facts,themes,time,cost,notice,question,answer,source) => ({
  id,type:'place',name,area,tag,image,desc,story,facts,themes,time,cost,notice,question,answer,source
});

export const places = [
  place('p1','Kampong Lorong Buangkok','Buangkok','LIVING HERITAGE',IMG.kampong,
    'Singapore’s last known surviving traditional mainland kampong, where heritage is still part of a living residential community.',
    'The value of Kampong Lorong Buangkok is not just its houses. It shows how community ties, everyday routines and a rural landscape became part of Singapore’s changing urban story.',
    ['Established in 1956','Chinese and Malay families lived here','Still a living residential community'],
    ['Living heritage','Community','Housing'], '45–60 min','Free',
    'Stay on public paths, keep noise low and do not photograph residents without permission.',
    'What makes this place different from a museum?', 'It is still a lived-in residential community.',
    'National Heritage Board · Kampong Lorong Buangkok'),

  place('p2','Tiong Bahru Air-Raid Shelter','Tiong Bahru','WARTIME · HOUSING',IMG.shelter,
    'A large air-raid shelter beneath Block 78 that reveals a wartime layer underneath a familiar housing estate.',
    'Built before World War II, the shelter shows how infrastructure can outlive the original emergency it was designed for and become part of a neighbourhood’s memory.',
    ['Built in 1939','Located beneath Block 78','Could accommodate up to about 1,600 people'],
    ['Wartime','Housing','Hidden heritage'], '30–45 min','Free',
    'Only enter when access is officially permitted.',
    'When was the shelter built?', '1939',
    'National Heritage Board · Tiong Bahru heritage materials'),

  place('p3','Fuyong Estate','Bukit Timah','EARLY HOUSING',IMG.fuyong,
    'An early housing estate that helps explain Singapore’s transition from low-rise settlements to modern public housing.',
    'Looking at earlier estates makes the housing story feel less abstract. Neighbourhoods changed gradually as Singapore expanded, built new infrastructure and improved housing conditions.',
    ['1950s-era housing development','Linked to early affordable housing','Neighbourhood-scale built heritage'],
    ['Housing','Urban change','Architecture'], '30–45 min','Free',
    'Explore public areas and respect current residents.',
    'What can old housing estates teach us?', 'They show how neighbourhoods changed as the city developed.',
    'Heritage / built-environment reference materials'),

  place('p4','Goh Chor Tua Pek Kong Temple','Balestier','1847 · COMMUNITY',IMG.gohChor,
    'A historic Balestier landmark founded by Hokkien labourers and closely connected to the area’s early development.',
    'Established in 1847, the temple connects Balestier’s plantation-era past with the communities that lived and worked in the area.',
    ['Established in 1847','Founded by Hokkien labourers','Part of the Balestier heritage area'],
    ['Community','Migration','Architecture'], '20–30 min','Free',
    'Dress and behave respectfully at a place of worship.',
    'When was Goh Chor Tua Pek Kong Temple established?', '1847',
    'Urban Redevelopment Authority / National Heritage Board'),

  place('p5','Balestier Market','Balestier','FOOD · COMMUNITY',IMG.balestierMarket,
    'A conserved market building where neighbourhood history and everyday food culture meet.',
    'Balestier Market began as a market for roadside vendors and is now part of the area’s food landscape. It shows how everyday places can become heritage.',
    ['Built in 1922','Conserved in 2003','Now functions as a food centre'],
    ['Food','Community','Everyday heritage'], '30–45 min','Free to enter',
    'Be considerate in busy dining areas.',
    'Why can a market be heritage?', 'Because ordinary food and trade can preserve community history.',
    'National Heritage Board · Balestier heritage trail'),

  place('p6','Former Malay Film Productions Studio','Balestier','FILM · ARTS',IMG.malayFilm,
    'A former film studio associated with Singapore’s Golden Age of Malay Cinema.',
    'The site links Balestier to the film industry and the production of Malay-language movies during an important period of Singapore’s cultural history.',
    ['Studio established in the 1940s','Associated with the Shaw Organisation','Connected to the Golden Age of Malay Cinema'],
    ['Arts & film','Community','Balestier'], '20–30 min','Free exterior view',
    'View from public areas where applicable.',
    'What kind of heritage is represented here?', 'Film and popular culture heritage.',
    'National Heritage Board / Roots'),

  place('p7','Maha Sasanaramsi Burmese Buddhist Temple','Balestier','MIGRATION · COMMUNITY',IMG.burmese,
    'A Burmese Buddhist temple that adds a migration story to Balestier’s already layered neighbourhood history.',
    'Its history reflects the presence of Burmese communities in Singapore and the way neighbourhoods can hold cultural links far beyond the buildings most people notice first.',
    ['Roots date to the 19th century','Current site opened in 1991','Burmese Buddhist heritage'],
    ['Migration','Community','Architecture'], '30 min','Free',
    'Follow the temple’s visitor guidelines.',
    'Why does this landmark matter to neighbourhood history?', 'It shows how migrant communities shaped Singapore’s cultural landscape.',
    'National Heritage Board / Roots'),

  place('p8','Thian Hock Keng Temple','Chinatown / Telok Ayer','1839 · WATERFRONT',IMG.thianHock,
    'A historic waterfront landmark connected to early Chinese migration and Singapore’s changing shoreline.',
    'Before land reclamation, Telok Ayer was beside the sea. Thian Hock Keng became a place where early Chinese immigrants gave thanks after their journeys, tying migration to the old waterfront.',
    ['Construction began in 1839','Originally close to the waterfront','Connected to early Hokkien immigrant communities'],
    ['Migration','Waterfront','Architecture'], '30–45 min','Free',
    'Dress and behave respectfully at a place of worship.',
    'Why is Telok Ayer important to the temple’s story?', 'It was part of Singapore’s former waterfront and landing area.',
    'Thian Hock Keng official site / VisitSingapore'),

  place('p9','Sri Mariamman Temple','Chinatown','1827 · COMMUNITY',IMG.sriMariamman,
    'Singapore’s oldest Hindu temple and an example of how different communities shared historic commercial districts.',
    'Its location in Chinatown shows that historic neighbourhoods were never shaped by only one community. Migration, work, trade and community institutions often overlapped.',
    ['Founded in 1827','South Bridge Road','Historic South Indian community landmark'],
    ['Migration','Community','Architecture'], '30 min','Free',
    'Follow visitor and photography guidelines.',
    'What does this place show about Chinatown?', 'Historic Chinatown has always included multiple communities.',
    'National Heritage Board / Roots'),

  place('p10','Jamae Chulia Mosque','Chinatown','1820s · TRADE',IMG.jamae,
    'A historic South Bridge Road mosque associated with Tamil Muslim traders and Singapore’s early port community.',
    'Its position beside other historic institutions is a visible reminder that different migrant groups used the same trading districts and built community spaces there.',
    ['Founded in the 1820s','South Bridge Road','Linked to Tamil Muslim heritage'],
    ['Migration','Trade','Community'], '20–30 min','Free',
    'Dress modestly and follow mosque visitor guidelines.',
    'Why are several different heritage institutions close together here?', 'The old port and trading districts drew many migrant communities.',
    'National Heritage Board / MUIS heritage materials'),

  place('p11','Sultan Mosque','Kampong Gelam','1820s · ROYAL PRECINCT',IMG.sultan,
    'A major Kampong Gelam landmark linked to the former Malay royal precinct and regional trade.',
    'Kampong Gelam grew around the former royal compound and became a busy district for trade, settlement and community life.',
    ['Original mosque built in the 1820s','Part of the former royal precinct','Connected to regional trade and community life'],
    ['Royal history','Trade','Community'], '30–45 min','Free',
    'Dress modestly and follow visitor guidelines.',
    'What else should be explored around this mosque?', 'The wider Kampong Gelam streets, former royal precinct and heritage businesses.',
    'National Heritage Board / Kampong Gelam heritage materials'),

  place('p12','Malay Heritage Centre','Kampong Gelam','ROYALTY · STORIES',IMG.malayHeritage,
    'A heritage centre in the former Istana Kampong Gelam that brings together Malay history, objects and community stories.',
    'The former royal compound provides a useful starting point for understanding Malay history in Singapore, including royalty, language, migration and cultural life.',
    ['Former Istana Kampong Gelam','Heritage museum and cultural centre','Located at Sultan Gate'],
    ['History','Community','Architecture'], '60–90 min','Check current admission',
    'Check current opening and gallery information before visiting.',
    'What was this site before it became a heritage centre?', 'It was the former Istana Kampong Gelam royal compound.',
    'Malay Heritage Centre / National Heritage Board'),

  place('p13','House of Tan Teng Niah','Little India','1890s · SHOPHOUSE',IMG.tanTeng,
    'A distinctive surviving house showing that Little India’s historic business and residential life involved several communities.',
    'The house is associated with Tan Teng Niah, a Chinese businessman whose businesses operated in Little India. It is a useful reminder that neighbourhood histories are often mixed rather than divided into separate boxes.',
    ['Built in the late 19th century','Associated with Tan Teng Niah','Little India landmark'],
    ['Migration','Architecture','Community'], '20 min','Free exterior view',
    'Keep entrances clear and respect nearby homes and businesses.',
    'What is unusual about this house being in Little India?', 'It reflects the mixed communities and businesses that shaped the area.',
    'National Heritage Board / Roots'),

  place('p14','Sri Veeramakaliamman Temple','Little India','19TH CENTURY · COMMUNITY',IMG.sriVeera,
    'A long-established Hindu temple closely tied to Serangoon Road and Little India’s community history.',
    'The temple helps explain why Serangoon Road became a major centre for the Indian community, with businesses, food, festivals and social institutions growing around it.',
    ['Established in the 19th century','Serangoon Road','Strong community and festival connections'],
    ['Migration','Community','Architecture'], '30 min','Free',
    'Follow temple visitor and photography guidelines.',
    'How does the temple connect to the neighbourhood?', 'It grew alongside the Indian community and businesses around Serangoon Road.',
    'National Heritage Board / Roots'),

  place('p15','Abdul Gafoor Mosque','Little India','1910 · ARCHITECTURE',IMG.abdulGafoor,
    'An ornate mosque reflecting Tamil Muslim community life and the trading history around Serangoon Road.',
    'The mosque developed from a prayer space serving a Tamil Muslim community and became a distinctive architectural landmark in Little India.',
    ['Current building completed in 1910','Tamil Muslim heritage','Serangoon Road area'],
    ['Migration','Trade','Architecture'], '30 min','Free',
    'Dress modestly and follow mosque visitor guidelines.',
    'What community history is visible here?', 'The history of Tamil Muslim settlement, trade and community life.',
    'MUIS / Singapore heritage materials'),

  place('p16','Little India Arcade','Little India','TRADES · SHOPS · FOOD',IMG.littleIndiaArcade,
    'A conserved shophouse cluster where traditional retail, crafts, food and neighbourhood activity meet.',
    'Little India’s heritage is not only about monuments. Shops, food businesses and traditional trades help keep the commercial side of the precinct visible.',
    ['Conserved shophouse cluster','Traditional shops and food','Part of the Serangoon Road heritage precinct'],
    ['Food','Trade','Everyday heritage'], '30–45 min','Free to enter',
    'Keep pathways clear and ask before photographing shop owners.',
    'What makes shops part of heritage?', 'They preserve everyday trades, foods and community practices.',
    'Singapore heritage precinct references'),

  place('p17','Joo Chiat Shophouses','Joo Chiat & Katong','PERANAKAN · ARCHITECTURE',IMG.jooChiat,
    'Colourful conserved shophouses that show the architectural and social history of Joo Chiat and Katong.',
    'Joo Chiat developed from a former rural area into a suburban neighbourhood. Its conserved shophouses and terrace houses show how architecture, business and community identity evolved together.',
    ['Conservation status since 1993','Mainly two-storey shophouses and terrace houses','Strong Peranakan influence'],
    ['Architecture','Peranakan','Urban change'], '30–45 min','Free',
    'These are living homes and businesses; keep noise low.',
    'Why are these shophouses important?', 'They preserve the built character of an early 20th-century neighbourhood.',
    'Urban Redevelopment Authority · Joo Chiat Conservation Area'),

  place('p18','Nagore Dargah','Telok Ayer','19TH CENTURY · MIGRATION',IMG.nagore,
    'A historic landmark associated with Indian Muslim merchants and Telok Ayer’s old waterfront district.',
    'Telok Ayer was an early landing and trading area. Nagore Dargah forms part of the layered heritage of a street where different migrant communities established institutions.',
    ['19th-century landmark','Indian Muslim heritage','Telok Ayer historic district'],
    ['Migration','Trade','Waterfront'], '20–30 min','Free exterior view',
    'Treat the site and surrounding community with respect.',
    'What wider story does this site belong to?', 'The story of migration and trade around the old waterfront.',
    'National Heritage Board / Telok Ayer heritage materials'),

  place('p19','Kwan Im Thong Hood Cho Temple','Bras Basah & Bugis','1884 · WATERLOO STREET',IMG.kwanIm,
    'A long-established Waterloo Street landmark within one of Singapore’s most concentrated heritage districts.',
    'Bras Basah-Bugis developed as a dense area of institutions, education, trade and community life. Waterloo Street is one of the clearest places to see these layers together.',
    ['Founded in 1884','Waterloo Street','Part of the Bras Basah-Bugis heritage area'],
    ['Community','Architecture','Urban history'], '20–30 min','Free',
    'Follow temple visitor guidelines.',
    'What makes Waterloo Street interesting for heritage?', 'Different historical institutions developed close together here.',
    'National Heritage Board / Roots'),

  place('p20','Geylang Serai Market','Geylang & Geylang Serai','FOOD · MARKET · COMMUNITY',IMG.geylang,
    'A living market where Malay food traditions, shopping and everyday community life meet.',
    'Heritage becomes easier to understand when it is connected to something people still do. Markets preserve food, trade and social routines as well as memories of a neighbourhood.',
    ['Geylang Serai cultural district','Traditional Malay food','Living market environment'],
    ['Food','Community','Everyday heritage'], '45–60 min','Free to enter',
    'Be considerate in busy market spaces.',
    'What makes a living market different from a museum?', 'People still use it as part of everyday life.',
    'National Heritage Board / Geylang Serai heritage materials'),

  place('p21','National Museum of Singapore','Civic District','19TH CENTURY · NATIONAL STORY',IMG.nationalMuseum,
    'A major museum for understanding Singapore through objects, stories, people and historical change.',
    'The museum gives context to many smaller neighbourhood stories. It can be paired with a walk through the Civic District to connect objects and historical narratives with the city around them.',
    ['Established in the 19th century','National collection and galleries','Civic District landmark'],
    ['National history','Museums','Urban history'], '90–120 min','Check current admission',
    'Follow museum visitor rules.',
    'Why pair a museum visit with a neighbourhood walk?', 'The museum gives background that can help make places outside the museum easier to understand.',
    'National Museum of Singapore'),

  place('p22','Changi Beach','Changi','WAR & MEMORY',IMG.changi,
    'A coastal area where wartime history, memory and present-day recreation overlap.',
    'Changi is part of a heritage trail focused on war and peace. Its story links military history, the Japanese Occupation and the lives of people who experienced wartime Singapore.',
    ['Part of Changi Heritage Trail','World War II history','Coastal public space'],
    ['Wartime','Memory','Landscape'], '45–60 min','Free',
    'Treat memorial and historical sites respectfully.',
    'What does Changi add to a heritage trip?', 'It connects wartime history with the landscape of present-day Singapore.',
    'National Heritage Board · Changi Heritage Trail'),

  place('p23','Koon Seng Road Shophouses','Joo Chiat & Katong','PRE-WAR · ARCHITECTURE',IMG.jooChiat,
    'A well-known row of pre-war shophouses that makes Joo Chiat’s architectural history visible at street level.',
    'Koon Seng Road is one of the most recognisable parts of Joo Chiat’s conservation landscape, showing how homes and street architecture can carry neighbourhood identity.',
    ['Pre-war shophouses','Located within the Joo Chiat conservation area','Known for colourful facades and decorative details'],
    ['Architecture','Peranakan','Living heritage'], '20–30 min','Free',
    'Keep noise low and do not obstruct residents.',
    'What should you look for while walking here?', 'Tiles, facade details, windows, doors and the way older homes meet modern street life.',
    'Urban Redevelopment Authority / National Heritage Board')
];

export const foods = [
  {id:'f1',type:'food',name:'Katong Laksa',region:'Peranakan · East Coast',image:IMG.laksa,desc:'A coconut-based noodle dish strongly associated with Katong and the East.',learn:'Food can reveal migration, adaptation and local identity. Katong-Joo Chiat is known for food traditions shaped by different communities.',facts:['Rice noodles in a rich coconut-based broth','Strongly associated with Katong','Part of Singapore’s wider food heritage'],themes:['Food','Peranakan','Neighbourhood'],source:'National Heritage Board / Singapore food heritage references'},
  {id:'f2',type:'food',name:'Kaya Toast & Kopi',region:'Nanyang breakfast',image:IMG.kaya,desc:'Toast, kaya, soft-boiled eggs and kopi — a familiar breakfast with a wider migration story.',learn:'The Nanyang breakfast connects food traditions, coffee shops and migration history.',facts:['Kaya is commonly served with toast','Often paired with kopi and soft-boiled eggs','Part of Singapore’s everyday food culture'],themes:['Food','Everyday life','Migration'],source:'National Heritage Board · food heritage references'},
  {id:'f3',type:'food',name:'Kueh',region:'Peranakan · Malay · Singapore',image:IMG.kueh,desc:'Colourful sweet and savoury snacks that carry ingredients, techniques and traditions across communities.',learn:'Kueh can be sweet or savoury and commonly uses ingredients such as rice, coconut and palm sugar. Different communities have contributed to the many forms found in Singapore.',facts:['Sweet and savoury varieties','Often uses coconut and palm sugar','Shared across several culinary traditions'],themes:['Food','Peranakan','Malay','Craft'],source:'National Heritage Board · Kueh / Intangible Cultural Heritage'},
  {id:'f4',type:'food',name:'Roti John',region:'Malay · Indian Muslim foodways',image:IMG.rotiJohn,desc:'A local sandwich showing how outside influences were adapted into Singapore’s food culture.',learn:'Roti John is a useful example of food changing through migration, street trade and local adaptation.',facts:['Malay traditional sandwich','Popular in Singapore and the region','Often prepared with an egg-and-meat mixture'],themes:['Food','Migration','Everyday life'],source:'Wikimedia Commons / Singapore food heritage references'},
  {id:'f5',type:'food',name:'Tau Sar Piah',region:'Traditional bakery food',image:IMG.tauSarPiah,desc:'A flaky pastry commonly associated with traditional bakeries and neighbourhood food culture.',learn:'Traditional pastries can preserve bakery techniques and memories even as neighbourhoods modernise.',facts:['Flaky pastry with bean filling','Sold by traditional bakeries','Commonly associated with old-school Singapore snack culture'],themes:['Food','Traditional trades','Neighbourhood'],source:'Singapore food heritage references'},
  {id:'f6',type:'food',name:'Hawker Culture',region:'Multicultural food heritage',image:IMG.hawker,desc:'Not one dish, but a social practice of eating, meeting and sharing food in community dining spaces.',learn:'Hawker centres bring food, space and community together and reflect influences from different immigrant groups.',facts:['Hawker centres act as community dining spaces','Inscribed on UNESCO’s Intangible Cultural Heritage list in 2020','Food traditions reflect multiple migrant influences'],themes:['Food','Community','Living heritage'],source:'National Environment Agency / UNESCO-related heritage references'}
];

export const cultures = [
  {id:'c1',type:'culture',name:'Chinese Singaporean heritage',tag:'MIGRATION · FOOD · COMMUNITY',image:IMG.thianHock,desc:'Explore migration, dialect groups, clan networks, food, festivals and neighbourhood institutions.',themes:['Migration','Food','Community']},
  {id:'c2',type:'culture',name:'Malay heritage',tag:'KAMPONG · LANGUAGE · COMMUNITY',image:IMG.malayHeritage,desc:'Explore kampong life, language, music, foodways and the history of Kampong Gelam.',themes:['Community','Language','Food']},
  {id:'c3',type:'culture',name:'Indian Singaporean heritage',tag:'MIGRATION · FOOD · COMMUNITY',image:IMG.sriVeera,desc:'Explore migration, businesses, food, festivals and neighbourhoods such as Little India.',themes:['Migration','Food','Community']},
  {id:'c4',type:'culture',name:'Peranakan culture',tag:'HOME · FOOD · CRAFT',image:IMG.jooChiat,desc:'Explore homes, food, craftsmanship and the mixed cultural influences found in Singapore and the wider region.',themes:['Peranakan','Food','Craft']},
  {id:'c5',type:'culture',name:'Burmese heritage in Singapore',tag:'MIGRATION · COMMUNITY',image:IMG.burmese,desc:'A reminder that Singapore’s cultural landscape includes communities beyond simple categories.',themes:['Migration','Community','Architecture']},
  {id:'c6',type:'culture',name:'Arab and Indian Muslim heritage',tag:'TRADE · COMMUNITY · FOOD',image:IMG.sultan,desc:'Explore trade networks, neighbourhoods, foodways and the institutions that developed around Singapore’s old port.',themes:['Trade','Community','Food']}
];

export const learnCards = [
  {id:'l1',question:'Why do so many different heritage institutions appear close together?',answer:'Historic Singapore grew around ports, trade routes and neighbourhoods where different migrant communities lived and worked near one another.',items:['Thian Hock Keng Temple','Sri Mariamman Temple','Jamae Chulia Mosque'],themes:['Migration','Community','Trade']},
  {id:'l2',question:'How did kampongs shape modern neighbourhoods?',answer:'Kampongs show an earlier neighbourhood form built around homes, informal community ties and shared everyday spaces. Some traces survive even as surrounding urban areas changed.',items:['Kampong Lorong Buangkok','Tiong Bahru'],themes:['Living heritage','Housing','Community']},
  {id:'l3',question:'Why is food such a useful way to learn heritage?',answer:'Food carries recipes, ingredients, techniques, businesses and memories from different communities. It also survives through everyday use, not only through museums.',items:['Katong Laksa','Kueh','Hawker Culture'],themes:['Food','Migration','Living heritage']},
  {id:'l4',question:'What does gotong royong mean in a heritage context?',answer:'It refers to mutual help and collective community effort. Looking at neighbourhood history can help connect the idea to everyday social life rather than treating it as a vocabulary word.',items:['Kampong Lorong Buangkok','Kampong Gelam'],themes:['Community','Living heritage']},
  {id:'l5',question:'Why are some heritage places hidden or easy to miss?',answer:'Some heritage survives underneath housing, beside modern roads or inside ordinary commercial streets. The building may look ordinary until its history is explained.',items:['Tiong Bahru Air-Raid Shelter','Balestier Market','Koon Seng Road Shophouses'],themes:['Hidden heritage','Architecture']},
  {id:'l6',question:'How can I visit living heritage respectfully?',answer:'Treat residential areas, places of worship and active businesses as places where people still live, work or practise. Observe from public areas, follow visitor rules and ask before taking photographs.',items:['Kampong Lorong Buangkok','Joo Chiat Shophouses','Religious landmarks'],themes:['Living heritage','Community']}
];

export const areas = ['All','Chinatown','Kampong Gelam','Little India','Balestier','Tiong Bahru','Joo Chiat & Katong','Telok Ayer','Bras Basah & Bugis','Geylang & Geylang Serai','Changi','Civic District','Buangkok','Bukit Timah'];
export const themes = ['All','Architecture','Community','Food','Migration','Wartime','Living heritage','Trade','Arts & film','Housing','Peranakan'];
