import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapPin, Search, Bookmark, Compass, CalendarDays, Ticket, UserRound, ChevronRight, ArrowUpRight, SlidersHorizontal, Sparkles, Clock3, Navigation, Check, Heart, X, WalletCards, Route, BookOpen} from 'lucide-react';
import './styles.css';

const places=[
 {id:1,name:'Kampong Lorong Buangkok',area:'Buangkok',type:'Living heritage',distance:'18 min',tag:'COMMUNITY',desc:'A surviving kampong landscape where everyday stories of Singapore’s past remain part of the present.',accent:'kampong'},
 {id:2,name:'Changi Village & Coastal Stories',area:'Changi',type:'Heritage trail',distance:'31 min',tag:'BY THE SEA',desc:'Explore stories of kampong life, coastal communities and traditions around Changi.',accent:'coast'},
 {id:3,name:'Jalan Sultan Stories',area:'Kampong Glam',type:'Culture & architecture',distance:'22 min',tag:'LOCAL STORIES',desc:'Look beyond the postcard landmarks and uncover stories woven into the streets around Kampong Glam.',accent:'shophouse'},
 {id:4,name:'Joo Chiat Then & Now',area:'Joo Chiat',type:'Architecture & food',distance:'16 min',tag:'THEN / NOW',desc:'See how conserved shophouses, family businesses and food traditions continue to shape the neighbourhood.',accent:'katong'}
];
const events=[
 {id:11,title:"Singapore's Beginnings: Coolies Footprints Heritage Tour",place:'Chinatown',date:'27 Jul – 21 Dec 2026',time:'90 min',from:35,cat:'Heritage',eligible:true},
 {id:12,title:'Kampong Root to Living Traditions',place:'Changi',date:'26 Jun – 31 Oct 2026',time:'360 min',from:60,cat:'Heritage',eligible:true},
 {id:13,title:'Savouring Chinatown: Art, Heritage & River Views',place:'Telok Ayer',date:'25 Jul – 4 Dec 2026',time:'180 min',from:80,cat:'Heritage',eligible:true},
 {id:14,title:'Crafting Moments: The Art of Letterpress',place:'Singapore',date:'Until 31 Aug 2026',time:'Workshop',from:80,cat:'Arts',eligible:true}
];

function App(){
 const [tab,setTab]=useState('discover'); const [query,setQuery]=useState(''); const [filter,setFilter]=useState('All');
 const [saved,setSaved]=useState(()=>JSON.parse(localStorage.getItem('hc_saved')||'[]'));
 const [balance,setBalance]=useState(()=>Number(localStorage.getItem('hc_balance')||100));
 const [points,setPoints]=useState(()=>Number(localStorage.getItem('hc_points')||180));
 const [modal,setModal]=useState(null); const [notice,setNotice]=useState('');
 const toggleSave=id=>{const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);localStorage.setItem('hc_saved',JSON.stringify(next));setNotice(next.includes(id)?'Saved to your collection':'Removed from your collection');setTimeout(()=>setNotice(''),1800)};
 const filtered=places.filter(p=>(filter==='All'||p.type.includes(filter)||p.area.includes(filter))&&(`${p.name} ${p.area} ${p.type}`.toLowerCase().includes(query.toLowerCase())));
 const redeem=e=>{if(!e.eligible){setNotice('This experience is not marked as SG Culture Pass eligible.');return} if(balance<e.from){setNotice('Your demo balance is not enough for this experience.');return} const b=balance-e.from;setBalance(b);localStorage.setItem('hc_balance',b);setModal(null);setPoints(x=>{const n=x+30;localStorage.setItem('hc_points',n);return n});setNotice='';setNotice('Experience added — continue to the official ticketing flow');setTimeout(()=>setNotice(''),2200)};
 return <div className="app">
  <aside className="sidebar">
   <div className="logo"><span className="logoMark">HC</span><div><b>heritage<br/>connect</b><small>Singapore</small></div></div>
   <div className="side-label">EXPLORE</div>
   <Nav icon={<Compass/>} label="Discover" active={tab==='discover'} onClick={()=>setTab('discover')}/>
   <Nav icon={<Route/>} label="Trails & places" active={tab==='places'} onClick={()=>setTab('places')}/>
   <Nav icon={<CalendarDays/>} label="Experiences" active={tab==='events'} onClick={()=>setTab('events')}/>
   <Nav icon={<Bookmark/>} label="Saved" active={tab==='saved'} onClick={()=>setTab('saved')} count={saved.length}/>
   <div className="side-spacer"/>
   <div className="pass-side"><div className="pass-icon"><WalletCards size={18}/></div><div><small>SG CULTURE PASS</small><strong>${balance}<span> left</span></strong></div><ChevronRight size={15}/></div>
   <Nav icon={<UserRound/>} label="My journey" active={tab==='journey'} onClick={()=>setTab('journey')}/>
  </aside>
  <main className="main">
   <header className="header"><div className="mobile-logo">heritage<span>connect</span></div><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search places, stories or experiences"/><kbd>/</kbd></div><button className="profile"><span>BH</span><ChevronRight size={15}/></button></header>
   {tab==='discover'&&<Discover setTab={setTab} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} filtered={filtered} saved={saved} toggleSave={toggleSave} setModal={setModal}/>} 
   {tab==='places'&&<Places filtered={filtered} filter={filter} setFilter={setFilter} saved={saved} toggleSave={toggleSave} setModal={setModal}/>} 
   {tab==='events'&&<Events setModal={setModal}/>} 
   {tab==='saved'&&<Saved saved={saved} toggleSave={toggleSave} setModal={setModal}/>} 
   {tab==='journey'&&<Journey points={points} balance={balance} saved={saved.length}/>} 
  </main>
  <nav className="mobile-nav"><Nav icon={<Compass/>} label="Discover" active={tab==='discover'} onClick={()=>setTab('discover')}/><Nav icon={<Route/>} label="Places" active={tab==='places'} onClick={()=>setTab('places')}/><Nav icon={<CalendarDays/>} label="Events" active={tab==='events'} onClick={()=>setTab('events')}/><Nav icon={<Bookmark/>} label="Saved" active={tab==='saved'} onClick={()=>setTab('saved')} count={saved.length}/><Nav icon={<UserRound/>} label="Journey" active={tab==='journey'} onClick={()=>setTab('journey')}/></nav>
  {modal&&<Modal item={modal} saved={saved} toggleSave={toggleSave} close={()=>setModal(null)} redeem={redeem}/>} {notice&&<div className="notice"><Check size={15}/>{notice}</div>}
 </div>
}
function Nav({icon,label,active,onClick,count}){return <button className={`nav ${active?'active':''}`} onClick={onClick}>{icon}<span>{label}</span>{count>0&&<i>{count}</i>}</button>}
function Discover({setTab,query,setQuery,filter,setFilter,filtered,saved,toggleSave,setModal}){return <div>
 <section className="welcome"><div><span className="overline">YOUR NEXT SINGAPORE STORY</span><h1>Go somewhere<br/><i>you haven't noticed.</i></h1><p>Discover places, people and experiences that make Singapore more than a skyline.</p><div className="heroActions"><button className="darkBtn" onClick={()=>setTab('places')}>Explore nearby <ArrowUpRight size={16}/></button><button className="textBtn" onClick={()=>setTab('events')}>See what's on <ChevronRight size={16}/></button></div></div><div className="heroVisual"><div className="stamp">FIELD<br/>NOTE<br/><b>01</b></div><div className="heroPhoto"><span>BUANGKOK</span><strong>Kampong<br/>Lorong<br/>Buangkok</strong><small>18 MIN FROM YOU</small></div><div className="heroCaption"><MapPin size={14}/> A different side of Singapore, still here.</div></div></section>
 <section className="quick"><div><small>YOUR CULTURE PASS</small><b>$100</b><span>credits available to discover local arts & heritage</span></div><div className="quickLine"/><div><small>THIS WEEK</small><b>12</b><span>experiences worth leaving home for</span></div><div className="quickLine"/><div><small>YOUR COLLECTION</small><b>{saved.length}</b><span>places saved to revisit</span></div></section>
 <section className="content"><div className="sectionTop"><div><span className="overline">CURATED FOR CURIOUS PEOPLE</span><h2>Start with a place.</h2></div><button className="linkBtn" onClick={()=>setTab('places')}>View all places <ArrowUpRight size={15}/></button></div>
 <div className="filters"><div className="filterSearch"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search heritage, food, craft..."/></div>{['All','History','Architecture','Food'].map(x=><button key={x} className={filter===x?'selected':''} onClick={()=>setFilter(x)}>{x}</button>)}<button className="filterIcon"><SlidersHorizontal size={15}/></button></div>
 <div className="placeGrid">{filtered.slice(0,4).map(p=><PlaceCard key={p.id} p={p} saved={saved.includes(p.id)} toggleSave={toggleSave} open={()=>setModal(p)}/>)}</div></section>
 <section className="week"><div className="sectionTop"><div><span className="overline">SG CULTURE PASS · DISCOVER EVENTS</span><h2>Use your $100 on an experience.</h2><p>Search, save and find something you actually want to do.</p></div><button className="linkBtn" onClick={()=>setTab('events')}>Browse all <ArrowUpRight size={15}/></button></div><div className="eventStrip">{events.slice(0,3).map(e=><EventCard key={e.id} e={e} open={()=>setModal(e)}/>)}</div></section>
 <section className="manifesto"><div className="manifestoMark">01</div><div><span className="overline">WHY HERITAGE CONNECT</span><h2>Heritage shouldn't<br/><i>sit behind glass.</i></h2></div><p>Existing heritage platforms help people learn. Culture Pass helps people access experiences. Heritage Connect sits in the gap — helping someone decide <b>where to go, why it matters and what to do next.</b></p></section>
 </div>}
function Places({filtered,filter,setFilter,saved,toggleSave,setModal}){return <div className="page"><PageTitle eyebrow="PLACES & TRAILS" title="Find the stories around you." text="Search by neighbourhood, interest or the kind of experience you want."/><div className="filters bigFilters">{['All','History','Architecture','Food'].map(x=><button key={x} className={filter===x?'selected':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="placeGrid four">{filtered.map(p=><PlaceCard key={p.id} p={p} saved={saved.includes(p.id)} toggleSave={toggleSave} open={()=>setModal(p)}/>)}</div></div>}
function Events({setModal}){return <div className="page"><PageTitle eyebrow="EXPERIENCES" title="Something worth going out for." text="Browse cultural experiences and heritage programmes. Eligible listings follow the SG Culture Pass model: in-person, ticketed experiences identified through the official scheme."/><div className="eventTabs"><button className="active">All</button><button>Heritage</button><button>Arts</button><button>Workshops</button></div><div className="eventList">{events.map(e=><EventRow key={e.id} e={e} open={()=>setModal(e)}/>)}</div></div>}
function Saved({saved,toggleSave,setModal}){const list=places.filter(p=>saved.includes(p.id));return <div className="page"><PageTitle eyebrow="YOUR COLLECTION" title="Places you want to remember." text="Save a place now. Decide when to go later."/>{list.length?<div className="placeGrid">{list.map(p=><PlaceCard key={p.id} p={p} saved toggleSave={toggleSave} open={()=>setModal(p)}/>)}</div>:<div className="empty"><Bookmark size={24}/><h3>Your collection is empty.</h3><p>Save a place when something catches your eye.</p></div>}</div>}
function Journey({points,balance,saved}){return <div className="page"><PageTitle eyebrow="MY JOURNEY" title="Your culture, in progress." text="A record of the places you've noticed, experiences you've tried and stories you've kept."/><div className="journeyGrid"><div className="journeyCard dark"><small>EXPLORER LEVEL</small><div className="levelNum">02</div><h3>Neighbourhood Seeker</h3><div className="bar"><span style={{width:`${Math.min(100,points/3)}%`}}/></div><div className="journeyMeta"><span>{points} points</span><span>{saved} saved</span></div></div><div className="journeyCard"><small>SG CULTURE PASS</small><div className="bigBalance">${balance}</div><p>remaining in your demo wallet</p><button className="darkBtn">Find an experience <ArrowUpRight size={15}/></button></div><div className="journeyCard"><small>YOUR NEXT CHALLENGE</small><h3>Then & Now</h3><p>Visit a place you've only seen online. Compare an old image with what you see today.</p><div className="challenge"><Sparkles size={16}/> +50 points</div></div></div><div className="journeyFeed"><span className="overline">RECENT ACTIVITY</span><div><Check/><section><b>Profile started</b><small>You joined Heritage Connect.</small></section><time>Today</time></div><div><Heart/><section><b>Collection updated</b><small>Keep saving places you want to explore.</small></section><time>Today</time></div></div></div>}
function PageTitle({eyebrow,title,text}){return <header className="pageTitle"><span className="overline">{eyebrow}</span><h1>{title}</h1><p>{text}</p></header>}
function PlaceCard({p,saved,toggleSave,open}){return <article className="placeCard"><button className="save" onClick={()=>toggleSave(p.id)}>{saved?<Heart fill="currentColor"/>:<Bookmark/>}</button><div className={`placeArt ${p.accent}`}><span>{p.tag}</span><strong>{p.name}</strong><small>{p.area} · {p.distance}</small></div><div className="placeInfo"><div><small>{p.type}</small><h3>{p.name}</h3></div><button onClick={open}>View story <ArrowUpRight size={14}/></button></div></article>}
function EventCard({e,open}){return <article className="eventCard"><div className="eventDate"><span>{e.date.split(' ')[0]}</span><b>{e.date.substring(4,10)}</b></div><div><span className="tinyTag">{e.eligible?'SG CULTURE PASS':'EXPERIENCE'}</span><h3>{e.title}</h3><p><MapPin size={13}/>{e.place} · <Clock3 size={13}/>{e.time}</p><strong>from ${e.from}</strong></div><button onClick={open}><ArrowUpRight size={16}/></button></article>}
function EventRow({e,open}){return <article className="eventRow"><div className="rowDate"><b>{e.date.split(' ')[0]}</b><span>{e.date.substring(4,10)}</span></div><div className="rowMain"><span className="tinyTag">{e.cat}{e.eligible?' · CULTURE PASS':''}</span><h3>{e.title}</h3><p>{e.place} · {e.time}</p></div><div className="rowPrice"><small>FROM</small><b>${e.from}</b></div><button onClick={open}><ArrowUpRight/></button></article>}
function Modal({item,saved,toggleSave,close,redeem}){const isEvent=!!item.from;return <div className="modalBack" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modalClose" onClick={close}><X/></button>{isEvent?<><span className="overline">{item.eligible?'SG CULTURE PASS ELIGIBLE':'EXPERIENCE'}</span><h2>{item.title}</h2><div className="detailGrid"><span><CalendarDays size={16}/>{item.date}</span><span><MapPin size={16}/>{item.place}</span><span><Clock3 size={16}/>{item.time}</span></div><p>This prototype mirrors the discovery and eligibility flow of SG Culture Pass. Actual identity verification and ticket checkout should continue through the official SG Culture Pass / authorised ticketing partner flow.</p><div className="priceBox"><div><small>FROM</small><b>${item.from}</b></div>{item.eligible&&<span>Uses Culture Pass credits</span>}</div><button className="darkBtn full" onClick={()=>redeem(item)}>{item.eligible?'Use demo credits & continue':'View experience'} <ArrowUpRight size={16}/></button></>:<><span className="overline">{item.tag}</span><h2>{item.name}</h2><p>{item.desc}</p><div className="storyBox"><BookOpen size={18}/><div><b>Why it matters</b><p>Heritage is more than a landmark. Look for the people, practices and changes that connect this place to Singapore today.</p></div></div><div className="modalActions"><button className="darkBtn" onClick={()=>toggleSave(item.id)}>{saved.includes(item.id)?'Saved':'Save place'} <Bookmark size={15}/></button><button className="textBtn" onClick={close}>Keep exploring <ChevronRight size={15}/></button></div></>}</div></div>}

createRoot(document.getElementById('root')).render(<App/>);
